name: Build, Release and Release Docker Image

on: [push]

jobs:
  build-release-deploy:
    runs-on: ubuntu-latest

    env:
      BUILD_PATH: 'build/libs/'
      DEPLOYMENT_PATH: 'deployment/'
      JAR_FILE_NAME: 'parts-list-management-thymeleaf-1.0.0.jar'

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build and Test with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build --no-daemon

      - name: Get commit hash for release
        id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build --tag benthor318/parts-list-management:${{ steps.commit.outputs.short }} .
          docker push benthor318/parts-list-management:${{ steps.commit.outputs.short }}
