name: build-and-deploy

on:
  workflow_run:
    workflows: ["build-test-scan"]
    types:
      - completed
  push:
    branches:
      - deployment

jobs:
  build-release-deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    env:
      BUILD_PATH: 'build/libs/'
      DEPLOYMENT_PATH: 'deployment/'
      JAR_FILE_NAME: 'parts-list-management-thymeleaf-1.0.0.jar'

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3 # https://github.com/marketplace/actions/setup-java-jdk
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Execute remote ssh commands using ssh key # https://github.com/marketplace/actions/ssh-remote-commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo killall -9 java || echo "No Java Process was running."

      - name: Copy file via scp using ssh key # https://github.com/marketplace/actions/scp-command-to-transfer-files
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: ${{ env.BUILD_PATH }}${{ env.JAR_FILE_NAME }}
          target: ${{ env.DEPLOYMENT_PATH }}
          strip_components: 2

      - name: Execute remote ssh commands using ssh key # https://github.com/marketplace/actions/ssh-remote-commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo java -jar ${{ env.DEPLOYMENT_PATH }}${{ env.JAR_FILE_NAME }} > ${{ env.DEPLOYMENT_PATH }}logs.log & 
