name: build-and-test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # https://github.com/marketplace/actions/checkout

      - name: Set up JDK 17
        uses: actions/setup-java@v3 # https://github.com/marketplace/actions/setup-java-jdk
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assemble

      - name: Test with Gradle
        run: ./gradlew test

      - name: JaCoCo Report
        run: ./gradlew jacocoTestReport

      - name: Upload code coverage results
        uses: actions/upload-artifact@v3 # https://github.com/marketplace/actions/upload-a-build-artifact
        with:
          name: code-coverage-report
          path: build/reports/jacoco/test/html/
