name: Hello World

on: [push]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    env:
      BUILD_PATH: 'build/libs/'
      DEPLOYMENT_PATH: 'deployment/'
      JAR_FILE_NAME: 'parts-list-management-thymeleaf-1.0.0.jar'

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build and Test with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Copy file via ssh key
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: ${{ env.BUILD_PATH }}${{ env.JAR_FILE_NAME }}
          target: ${{ env.DEPLOYMENT_PATH }}
          strip_components: 2

      - name: Execute remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          # The redirection of output into a file is necessary. Otherwise, the script would not exit.
          script: |
            java -jar ${{ env.DEPLOYMENT_PATH }}${{ env.JAR_FILE_NAME }} > ${{ env.DEPLOYMENT_PATH }}logs.log &
