name: Hello World

on: [push]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    env:
      BUILD_PATH: 'build/libs/'
      DEPLOYMENT_PATH: 'deployment/'
      JAR_FILE_NAME: 'parts-list-management-thymeleaf-1.0.0.jar'

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build and Test with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Get commit hash for release
        id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          # This token is provided by GitHub Actions, you do not need to create your own token.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.commit.outputs.short }}
          release_name: Release ${{ steps.commit.outputs.short }}
          body: |
            Changes in this Release
            - first release of the demo branch 
